name: PR

on:
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        uv run flake8 clamav_rest.py config.py --count --show-source --max-line-length=127 --statistics

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Install the project
      run: uv sync --locked --all-extras --dev

    - name: Run tests
      run: |
        uv run python -m pytest
